version: '3.0'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "8081:8080"
    environment:
      - SERVICES=serverless
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
